#include <stdlib.h>
#include <stdio.h>
#include <getopt.h>
#include <errno.h>
#include <string.h>

struct option long_opts[] = {
  {"--first",1,NULL,'f'},
  {"--input",1,NULL,'i'},
  {"--last",1,NULL,'l'},
  {"--natoms",1,NULL,'n'},
  {"--output",1,NULL,'o'},
  {"--periodic",0,NULL,'p'},
  {NULL,0,NULL,0}
};
static const char short_opts[] = "f:i:l:n:o:p";

int main(int argc, char **argv)
{

  int natoms,ifbox = 0;
  size_t num_lines,chars_per_snap;
  int snap_number = -1, last_snap = -1;
  char *buf = NULL;
  FILE *input = stdin;
  FILE *output = stdout;
  char optflag;
  
  while((optflag = getopt_long(argc,argv,short_opts,long_opts,NULL)) != -1)
    {
      switch(optflag)
	{
	case 'i':
	  input = fopen(optarg,"r");
	  if(input == NULL)
	    {
	      fprintf(stderr,"Could not open %s\nReason: %s\n",optarg,strerror(errno));
	      exit(errno);
	    }
	  break;
	case 'o':
	  output = fopen(optarg,"w");
	  if(output == NULL)
	    {
	      fprintf(stderr,"Could not open %s\nReason: %s\n",optarg,strerror(errno));
	      exit(errno);
	    }
	  break;
	case 'l':
	  if(sscanf(optarg,"%d",&last_snap) != 1)
	    {
	      fprintf(stderr,"Could not read integer value: %s\n",optarg);
	      exit(errno);
	    }
	  break;
	case 'f':
	  if(sscanf(optarg,"%d",&snap_number) != 1)
	    {
	      fprintf(stderr,"Could not read integer value: %s\n",optarg);
	      exit(errno);
	    }
	  break;
	case 'n':
	  if(sscanf(optarg,"%d",&natoms) != 1)
	    {
	      fprintf(stderr,"Could not read integer value: %s\n",optarg);
	      exit(errno);
	    }
	  break;
	case 'p':
	  ifbox = 1;
	  break;
	default:
	  fprintf(stderr,"Unknown flag: %f",optflag);
	  exit(-1);
	}
    }

  if(last_snap < -1)
    last_snap = snap_number;

  num_lines = (natoms*3)/10;
  if(natoms*3%10 != 0)
    num_lines++;
	
  chars_per_snap = natoms*3*8 + num_lines;
  if(ifbox != 0)
    chars_per_snap += 25;
  
  buf = (char*)calloc(chars_per_snap + 1,sizeof(char));
  getline(&buf,&num_lines,input);// skip title
  
  fseek(input,chars_per_snap*(snap_number-1) + strlen(buf),SEEK_SET);// snap_number is ONE-indexed
  fprintf(output,"trajectory generated by mtraj\n");
  for(;snap_number <= last_snap;snap_number++)
    {
      fread(buf,chars_per_snap,sizeof(char),input);
      fwrite(buf,chars_per_snap,sizeof(char),output);
      fflush(output);
    }

  if(input != NULL && input != stdin)
    fclose(input);
  if(output != NULL && output != stdout)
    fclose(output);
  if(buf != NULL)
    free(buf);
  return 0;

  
}

